### ISSUE TITLE
Bad typing in write method

### ISSUE THREAD

**Issue by mwawrzyniak-57** [lengow/plugin-magento2#37]
Hi,

Since last version 1.6.7, there is an issue in `Model/Export/Feed.php:183`.
Indeed, this method must have the `$maxCharacter` variable of type `int` and not `bool`.
In this method,` $this->getBody($data, $isFirst, $maxCharacter);` takes as parameter $maxCharacter of type int and not bool.

The fix :

```
diff --git a/Model/Export/Feed.php b/Model/Export/Feed.php
index 016320f..6ca4e12 100644
--- a/Model/Export/Feed.php
+++ b/Model/Export/Feed.php
@@ -176,11 +176,11 @@ class Feed
      * @param string $type (header, body or footer)
      * @param array $data export data
      * @param boolean|null $isFirst is first product to export
-     * @param boolean|null $maxCharacter Max characters for yaml format
+     * @param int $maxCharacter Max characters for yaml format
      *
      * @throws Exception
      */
-    public function write(string $type, array $data = [], bool $isFirst = null, bool $maxCharacter = null): void
+    public function write(string $type, array $data = [], bool $isFirst = null, int $maxCharacter = 0): void
     {
         switch ($type) {
             case self::HEADER:

```

**Comment by lattaai12** [comment]
Hello, I tried to solve the issue.

This is what I did:

Changed the type of $maxCharacter parameter from bool to int in the write method signature and PHPDoc. Also updated the default value to 0.

You can review changes in this commit: https://github.com/lattaai12/lengow-plugin-magento2-37/commit/e13086997f857a31260b50b5754d33509276ffbc.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
